
package:
  name: dipde
  version: 0.2.1

source:
  git_url: https://github.com/nicain/dipde_dev.git
  git_rev: v0.2.1 [py2k]
  git_rev: python3_v0.2.1 [py3k]

build:
  number: 3

requirements:
  build:
    - python
    - numpy
    - matplotlib
    - scipy
    - sympy
    - pandas
    - pyzmq
    - mpi4py

  run:
    - python
    - numpy
    - matplotlib
    - scipy
    - sympy
    - pandas
    - pyzmq
    - mpi4py

test:

  requires:
    - numpy
    - scipy
    - sympy
    - pandas
    - pyzmq
    - mpi4py
    - pytest
    - matplotlib

about:
  summary: https://github.com/nicain/dipde_dev/blob/master/README.md